services:
  - type: web
    name: stemverse
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn stemverse.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stemverse.settings
      - key: PYTHON_VERSION
        value: 3.11
