# Generated by Django 5.2.3 on 2025-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
