# Generated by Django 5.2.3 on 2025-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_photos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='STEMVerse', max_length=100),
        ),
    ]
